import os
# print(os.name)
# print(os.uname())
# print(os.environ)
# print(os.environ.get('SESSION'))
# print(os.getcwd())
# print(os.listdir(r"/home/km/PycharmProjects"))
# os.mkdir("sunck")
# os.rmdir("sunck")
# print(os.stat("os模块.py"))
os.system("msconfig")